// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnW9W83PHgn2lu3_Wqd2RxWVCewJQidoE',
    appId: '1:851190563980:web:88e91bc0630476cec4e7a9',
    messagingSenderId: '851190563980',
    projectId: 'insta-22ba4',
    authDomain: 'insta-22ba4.firebaseapp.com',
    storageBucket: 'insta-22ba4.appspot.com',
    measurementId: 'G-BTLN3LM298',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVpZRsyBFR11aZ96pdikevVi1xHIDQidE',
    appId: '1:851190563980:android:36452ee3a799647dc4e7a9',
    messagingSenderId: '851190563980',
    projectId: 'insta-22ba4',
    storageBucket: 'insta-22ba4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBUFN9EugMFeflpUFB_6EH7hIjk9akCRU',
    appId: '1:851190563980:ios:c8b6c25eed6253c2c4e7a9',
    messagingSenderId: '851190563980',
    projectId: 'insta-22ba4',
    storageBucket: 'insta-22ba4.appspot.com',
    iosClientId: '851190563980-dsnb8giahjuueeel44cdu3u2es1jut7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBUFN9EugMFeflpUFB_6EH7hIjk9akCRU',
    appId: '1:851190563980:ios:c8b6c25eed6253c2c4e7a9',
    messagingSenderId: '851190563980',
    projectId: 'insta-22ba4',
    storageBucket: 'insta-22ba4.appspot.com',
    iosClientId: '851190563980-dsnb8giahjuueeel44cdu3u2es1jut7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );
}
